### ISSUE TITLE
REPORTE DE PRACTICA ENTREVISTA

### ISSUE THREAD

**Issue by IrvinSanchez-dev** [SistemasTecTlaxiaco/actividad-7-practica-de-entrevista-dinamita#1]
[REPORTE DE PRACTICA ENTREVISTA.pdf](https://github.com/user-attachments/files/17551708/REPORTE.DE.PRACTICA.ENTREVISTA.pdf)
INTEGRANTES: DIEGO CRUZ CRUZ
MARCO URIEL ROSAS GARCIA
IRVIN JIMENEZ SANCHEZ

**Comment by Daniel-Velasco-Lopez** [comment]
En base a la rubrica obtuvieron el 30%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
